# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_REGION: westeurope
  ENVIRONMENT: dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs the Bicep linter to ensure build is successful
      - name: Run Bicep linter
        run: az bicep build --file azure.deploy.bicep

  validate:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1.0.8
        name: Run preflight validation
        with:
          deploymentName: ${{ github.run_number }}
          scope: subscription
          region: ${{ env.AZURE_REGION }}
          template: ./azure.deploy.bicep
          parameters: azure.deploy.parameters.json
          deploymentMode: Validate

  preview:
    runs-on: ubuntu-latest
    needs: [lint, validate]
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/cli@v1
        name: Run what-if
        with:
          azcliversion: 2.35.0
          inlineScript: |
            az deployment sub what-if \
              --location ${{ env.AZURE_REGION }} \
              --template-file azure.deploy.bicep \
              --parameters azure.deploy.parameters.json
